import type { Metadata } from "next";
// import localFont from "next/font/local";
import "@/components/craft/craft.css";
import "./globals.css";
import { Providers } from "@/providers/providers";
import { Inter } from "next/font/google";
import { twMerge } from "tailwind-merge";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={twMerge(inter.className, "antialiased bg-background")}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
